FROM node:20-bookworm
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY prisma ./prisma
RUN npx prisma generate
COPY tsconfig.json nest-cli.json ./
COPY src ./src
EXPOSE 3000
CMD ["npm", "run", "start:dev"]
